php:
  build: .
  dockerfile: Dockerfile
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - ./:/var/www/
  links:
   - db
db:
  image: mysql:5.7
  ports:
   - "3306:3306"
  volumes:
   - /var/lib/mysql
  environment: 
   - MYSQL_ROOT_PASSWORD=coingolive
   - MYSQL_DATABASE=coingolive